import { FileText, Users, Table, Type, Hash, Calendar, DollarSign, Mail, Star, CheckCircle } from "lucide-react"

export const datasets = [
  { name: "random_kdd_dataset.csv", icon: FileText, active: true },
  { name: "50x50_table.csv", icon: FileText },
  { name: "bad_data.csv", icon: FileText },
]

export const schema = {
  users: {
    icon: Users,
    columns: [
      { name: "product_id", type: "integer", icon: Hash },
      { name: "product_name", type: "varchar", icon: Type },
      { name: "price", type: "decimal", icon: DollarSign },
    ],
  },
  other_table: {
    icon: Table,
    columns: [
      { name: "column_a", type: "text", icon: Type },
      { name: "column_b", type: "integer", icon: Hash },
    ],
  },
}

export const cleaningActions = [
  "Remove Rows with Null Values in Category",
  "Remove Rows with Invalid Email Format",
  "Remove Duplicate Email Entries",
  "Remove Rows with Invalid Date Separator in Join Date",
  "Remove Rows with Invalid Date Components in Join Date",
  "Remove Rows with Negative Ratings",
  "Remove Rows with Null Values in Age",
  "Remove Rows with Null Values in Salary",
]

export const queryHistory = [
  {
    id: 1,
    title: "Filter Users by Age > 30",
    sql: "SELECT id, name, age FROM users WHERE age > 30;",
    timestamp: "2023-10-27T10:00:00Z",
    prompt: "Show me all users older than 30",
    mode: "ask",
    model: "GPT-4o",
  },
  {
    id: 2,
    title: "Count Users by Category",
    sql: "SELECT category, COUNT(*) as user_count FROM users GROUP BY category;",
    timestamp: "2023-10-27T09:45:00Z",
    prompt: "Count how many users are in each category",
    mode: "ask",
    model: "GPT-4o",
  },
  {
    id: 3,
    title: "Find Users with Invalid Emails",
    sql: "SELECT * FROM users WHERE email NOT LIKE '%@%.%';",
    timestamp: "2023-10-26T15:20:00Z",
    prompt: "Find all users with invalid email addresses",
    mode: "action",
    model: "DeepSeek-V2",
  },
  {
    id: 4,
    title: "Calculate Average Salary",
    sql: "SELECT AVG(salary) as average_salary FROM users;",
    timestamp: "2023-10-26T14:10:00Z",
    prompt: "What is the average salary of all users?",
    mode: "ask",
    model: "GPT-3.5",
  },
]

export const tableData = [
  {
    id: 1,
    name: "User_1",
    age: 58,
    salary: 51319,
    email: "user1@example.com",
    joinDate: "2021-09-13",
    category: "C",
    score: 88,
    rating: 1.1,
    originalRowIndex: 0,
  },
  {
    id: 2,
    name: "User_2",
    age: 25,
    salary: 78520,
    email: "user2@example.com",
    joinDate: "2022-09-16",
    category: null,
    score: 19,
    rating: 3.2,
    originalRowIndex: 1,
  },
  {
    id: 3,
    name: "User_3",
    age: 19,
    salary: 76566,
    email: "user3@example.com",
    joinDate: "2021-06-15",
    category: "A",
    score: 90,
    rating: 5,
    originalRowIndex: 2,
  },
  {
    id: 4,
    name: "User_4",
    age: 45,
    salary: 57460,
    email: "user4@example.com",
    joinDate: "2020-06-25",
    category: "A",
    score: 27,
    rating: 2.4,
    originalRowIndex: 3,
  },
  {
    id: 5,
    name: "User_5",
    age: 35,
    salary: 117841,
    email: "user5@example.com",
    joinDate: "2020-02-21",
    category: "B",
    score: 999,
    rating: 3.6,
    originalRowIndex: 4,
  },
  {
    id: 6,
    name: "User_6",
    age: 33,
    salary: 64993,
    email: "invalid_email",
    joinDate: "2022-04-11",
    category: "C",
    score: 8,
    rating: 4.1,
    originalRowIndex: 5,
  },
  {
    id: 7,
    name: "User_7",
    age: 45,
    salary: 115093,
    email: "user7@example.com",
    joinDate: "2021-02-12",
    category: "A",
    score: 53,
    rating: 3.6,
    originalRowIndex: 6,
  },
  {
    id: 8,
    name: "User_8",
    age: 32,
    salary: null,
    email: "user8@example.com",
    joinDate: "2023-02-27",
    category: null,
    score: 52,
    rating: 4,
    originalRowIndex: 7,
  },
  {
    id: 9,
    name: "User_9",
    age: 57,
    salary: 114939,
    email: "user9@example.com",
    joinDate: "invalid_date",
    category: "A",
    score: 42,
    rating: 4.8,
    originalRowIndex: 8,
  },
  {
    id: 10,
    name: "User_10",
    age: 55,
    salary: 39258,
    email: "user10@example.com",
    joinDate: "2021-03-26",
    category: "B",
    score: 999,
    rating: 2.7,
    originalRowIndex: 9,
  },
  {
    id: 11,
    name: "User_11",
    age: 24,
    salary: 109840,
    email: "user11@example.com",
    joinDate: "2021-05-26",
    category: "C",
    score: 69,
    rating: 1.1,
    originalRowIndex: 10,
  },
  {
    id: 12,
    name: "User_12",
    age: 61,
    salary: 113227,
    email: "invalid_email",
    joinDate: "2023-04-27",
    category: null,
    score: 59,
    rating: 1.1,
    originalRowIndex: 11,
  },
  {
    id: 13,
    name: "User_13",
    age: 65,
    salary: 52431,
    email: "user13@example.com",
    joinDate: "2021-05-22",
    category: "A",
    score: 53,
    rating: 1.6,
    originalRowIndex: 12,
  },
  {
    id: 14,
    name: "User_14",
    age: null,
    salary: 100010,
    email: "user14@example.com",
    joinDate: "2022-08-26",
    category: "C",
    score: 7,
    rating: 1.5,
    originalRowIndex: 13,
  },
  {
    id: 15,
    name: "User_15",
    age: 52,
    salary: 62087,
    email: "user15@example.com",
    joinDate: "2023-02-17",
    category: "C",
    score: 999,
    rating: 3.7,
    originalRowIndex: 14,
  },
  {
    id: 16,
    name: "User_16",
    age: 23,
    salary: null,
    email: "user16@example.com",
    joinDate: "2021-02-20",
    category: "A",
    score: 26,
    rating: 3.8,
    originalRowIndex: 15,
  },
  {
    id: 17,
    name: "User_17",
    age: 55,
    salary: 51417,
    email: "user17@example.com",
    joinDate: "2020-09-17",
    category: "C",
    score: 53,
    rating: 1.9,
    originalRowIndex: 16,
  },
  {
    id: 18,
    name: "User_18",
    age: 45,
    salary: 90589,
    email: "invalid_email",
    joinDate: "invalid_date",
    category: "C",
    score: 49,
    rating: 3.8,
    originalRowIndex: 17,
  },
  {
    id: 19,
    name: "User_19",
    age: 20,
    salary: 79735,
    email: "user19@example.com",
    joinDate: "2021-01-12",
    category: null,
    score: 98,
    rating: 4.1,
    originalRowIndex: 18,
  },
  {
    id: 20,
    name: "User_20",
    age: 19,
    salary: 65382,
    email: "user20@example.com",
    joinDate: "2020-04-12",
    category: "C",
    score: 999,
    rating: 1.7,
    originalRowIndex: 19,
  },
]

export const tableHeaders = [
  { key: "id", label: "ID", icon: Hash },
  { key: "name", label: "Name", icon: Users },
  { key: "age", label: "Age", icon: Hash },
  { key: "salary", label: "Salary", icon: DollarSign },
  { key: "email", label: "Email", icon: Mail },
  { key: "joinDate", label: "Join Date", icon: Calendar },
  { key: "category", label: "Category", icon: CheckCircle },
  { key: "score", label: "Score", icon: Hash },
  { key: "rating", label: "Rating", icon: Star },
  { key: "originalRowIndex", label: "originalRowIndex", icon: Hash },
]
